apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: charizard-chard
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default  #update namespace name if you wish
    name: in-cluster   #update cluster name if its different
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: charizard-chart
    helm:
      values: |
        controller:
          service:
            type: ClusterIP