project: default
source:
  repoURL: https://github.com/catemlitten/helm-charts.git
  path: pikachu
  helm:
    parameters:
      - name: namespace
        value: default
destination:
  server: https://kubernetes.default.svc
  namespace: default
syncPolicy:
  automated:
    prune: true
    selfHeal: false
  syncOptions:
    - CreateNamespace=false